# -*- coding: utf-8 -*-

META = {
    "meta.dex.size": {4765888},
    "meta.sha1": {"9c14d537a7adb4cfc43d291352f73e05e0ccdd4a"},
    "meta.market": {"anzhi"},
    "meta.pkg.code": {121},
    "meta.dex.date": {"2016-04-05 17:58:46"},
    "meta.apk.size": {10386469},
    "meta.vt.score": {0},
    "meta.sha256": {"0000003b455a6c7af837ef90f2eaffd856e3b5cf49f5e27191430328de2fa670"},
    "meta.pkg.name": {"com.zte.bamachaye"},
    "meta.md5": {"3edfc78ab53521942798ad551027d04f"},
    "meta.vt.date": {"2016-06-15 15:26:44"},
}


LABEL = {"label.type": {"adware"}, "label.family": {"kuguo"}}

SOURCE = {
    "source.class.inter": {
        "landroid/content/dialoginterface$oncancellistener;",
        "landroid/content/dialoginterface$onclicklistener;",
        "landroid/content/serviceconnection;",
    },
    "source.method.code": {
        "17d5a3e3e7515b78d421fe8bfee77daf3b4a9222afe6d84e63bde5416c6a19e8",
        "d97f4846ffb0f6e12884b224016bf7aad6f7190d304f8a81e081c096ef235a24",
        "631687f3ae40ad5c6b04ca090b15c656e0a883f466dcbeee4631f88143aba42c",
        "a27abc21faa5d9bd308d2911cfc830c92c55e0affcfe4fbdab83db9980dddb75",
        "6da0126a7857a14beea5688913b6b38414ac21ed62fb7115cc988536882d8aed",
        "229c0492b7b54cbaa446984c503ba4e12fd1c596c22904c93436a7a15191eba2",
        "a19fd22dbae7853e9a2f928bf297a54b1a1ab9d56de47fed217442c10b50c239",
        "db960af31e33cdd016bb4807be6c359d88f90f09ab70f1f28cf9df533218da59",
        "4ae5c440825ba6e97f989f76bf1e746ec28fb63642e23029cc2cb16e951544c9",
        "8946a073a0cf96778c58a976698510da6e2f675174f222aaed4eac95c8beaf5c",
        "dce595e3d2fbd672d1e8e6eb07c8700c8c9549d0f104805383bd0fc664e276eb",
        "425876f3ceb1bf7d7f11a7b53ab978ade01f47feb4c59523673e771f0ea945ce",
        "578cb48f1bc0a3648bb6bb51a0ec8de837d39d71eabe688ad63a090df823b6e1",
        "576c069c7696cdbe833be3c4762172ae695d8f65f20965af531f3ba355ff1da5",
        "ba0314aa905f7c980531bbdad356f35e0127df58f83452bf9ad16deafa5df3bf",
        "dcf8e84cb9a7ca1136a8ef0bea07dc4d5f696d1e828a15b61a13e48bccac1232",
        "d7cd09f1709f47c41df2748c5fb5cc3c61caa0872d839a912e3fa040e2dcafa1",
        "4147db96d0278afddeefb3eb21cef8d55d566000ffe23cdd5a9454689dae443c",
        "940f9909c0bcf188e957084990b3ef80526813964a2c5787e2fe9e212eaf220d",
        "26c6e87032e82412289878e8a7fa52e9549afc98a4fedfb08e14e2c362ad4811",
        "fbd65ccdaaf4c332b10891e828595cfea7b7e171d101f5306672564c690c54b0",
        "0b824653ed7d7dffe14ccffff6398e62fc706d7f8845b9c12379f30f9edef314",
        "2a243e43bea811d698e7f1da91cc19accdd5c37ef3fee977274cd06573322baf",
        "4da30b73203d20a89f99d9303e24c76af74cbf1e8d59852bd87bac7e93d9f33e",
        "03b0c7693d4c47fe0ecb66ba15498e11e8e96a5dc821c751bce0f363680ed919",
        "ca6464f4cced04a39380b6ac80c31caea006f15262b55432a90be96b420a6366",
        "52e822047a7918e68b351404349e7035a4824b01ccc36a237c913bf00de3591e",
        "58b5b2bab960736564f561de3c42e788b31c0b5038314454640c85df698f54e6",
        "ac087ea390419b9e6d08615c7af5e6bd8c31be973772aa0b822cca9312e6dcef",
        "479747c323d4ca9c5b2488750c2a16165c5d8360b2fa04286969300f50bbb7d7",
        "2289ce5d6c5438312e89d71fdfaecaea349efeb626fdd5c3050bd6a177aa2d3d",
        "5cc9fb237b9695f246b8842329305e8b33aff1eefe1d981e638d816cdbe8517e",
        "10e18e427dd5abd225aad51ca4ab7529664f557b2977de6196bcde4d9747d730",
        "298aa7386b775f431f26e63925c2cc3fd2eaacda6aafc98a57dd2b094a11d323",
        "1b717b994ff0ea76248ee7ed773b86f6082e27c324659dda67cc2df814d6a04e",
        "0e1a4a56bb3ed8799896027989a7961f32f91b6f7dc772b5d5b82ce76566ba3f",
        "eaaf0b7b22f96c1fbd2ede3de72c5c27a328d7d2a00158e2aa27f0a156197916",
        "6f62caf8bb4a7ade0cb4d832abce82556a0195fbca6bb322fc3571bb131ae569",
        "4ea489911c940b0f9eb6b71d2bce737a5c906abb92662d85ff487e8f1b149ede",
        "5dbfd387c1029597795aaea87d35daf0a2530f70132af9701350e144369365d8",
        "610342375ef8a344a6e93ca2309ff7a100342cb8de752d22b4c12c6b43299e98",
        "e33929826ce0df1486e9179c06eedba707e4df87279a2618c7831ea6b6c77b29",
        "1f8a1431de04c9968f5d46ee470451c4db733ac83fb0f2c6ac2f4f482fdb2e97",
        "17e872aa76dde502b68bf1fb9a199aa335d40a66fb02078e69e8e14ee869bc75",
        "7c82a388be1c5afc444a04f6a7983b4c526de20ab0d24c621daaa2918f692a87",
        "7ec3ff41850dffc11928f89dc97440eee99ea040f2032b8356d94dc2e665aab5",
        "130fa475ffca52384182453ed39cf9ca04ffb74e17136cad2f520e74cb60251c",
        "439af28f0a495312c18e79df697ee481ec61539f44d8000e6ccacc4b4e89d0af",
        "26a81f65d0ea2b6adc3de618f6e5b6acd5e1b908829e4ba657f5f941de03da2f",
        "26dbad10efd7d6445a8809e4a5ce5baaa0379012aded528acae40616712df381",
        "2b7be970a17dccd6ab5fff48d5fb14bd7887aede0f37864ea43995db7dff43ba",
        "1f926273775f21d4b86e8089460f6efa65d8fe854d86168b39571db7f0ee6134",
        "82f03ffbe636474ab6ae342e5d6802dfae3d6d08ed1e69860a7f0bd3ed577311",
        "5c68c7efaa2f03591754c564d52722f9ad09642230aecaa2272e8a6790a655c2",
        "740cd04866e3a0a8e488bda152ac17dfcc438982fa2e2fc5e4d73271667796a2",
        "ae0d7427451fddc54826b0aa41a6f8dd5c8c8b44bf9a544df669d0d203837519",
        "6377ec4a032008f7ab7570ed0f1a7007247d658e0ca0006fc48262545887caf3",
        "a7c9fbe6e2eb5e5ac0d6073a4b09aba0f8c8345db91328565d6f11eb3320162f",
        "fc06021553a049a2d3187a80b8a27f8ddb802d5f1a8f11a3296229379be46ecd",
        "92f1b4feebbe8a781c18bfcd345ebe663b7eb4b8ce6a9f56bc03b951f497bebb",
        "e8050d00fcb317180216da44e1889e5eeec6d6ee115e161c928012c1b7a5ce53",
        "2bdc8a7cf35d8db4688234ec49e8cf101d93f89e94111ae4e3dd04aeac6ae694",
        "1b22dd3801b52c1b077e5de333e66c96863e6b30682cdbf1f7cc4737da013bbc",
        "3bb398c535b1987ccecf2d8e491647dd82b2fb6c4fc1a4d3202cfa3727029c21",
        "34c53810f9056377de8307db13ba337fdc6c641f9ee7e78261e111f50f1f1dbf",
        "383817f52695854c6b7e422cbdc6670efa6bcdd8656586f2a012aaa490471ff2",
        "c39bd59c47e6ea3b4677b9ed39117d75b264d6eb6be62cdacb7810aee1f4f59f",
        "d02ab6aa685d67cce603d2bd107deb05b741d2cf212c5f717fcb8adc033cef46",
        "b34894989cbc102c080111c4bd2a8efc82e8e87b2b035e4ad3c374252f6ff0c7",
        "84b18f479bb74029ba3fd1915f0e0f49623034a816ce489b851fefe3bbcdfe33",
        "0b08253602f9a9a6cff1bf59649492682d61a70aacf234ec8f9f26ad1044b034",
        "7a09405c506e0f196b4b50556cfc19f5a980b5098bce26f751682b2277ecddbc",
        "35994bf08ae4c153dd0b3162dde6f75d025e0d3a58674716e1bbefefc2c2b80f",
        "c203fd28745e9590dec54fa248725d0709bcacaf2aa8a5a8949900581060beee",
        "9164cbea5d456d99f9b1034b1924ecfb946e48685c83e47d53b4952f4a2110a8",
        "ffff3169b7965b0d0f2f626f7b7477878d6247dca046031415ab4dd8d23010d3",
        "56344090c52ad009990ea99d726b5411d7484408a6e4a3e1bc4bcb2583139f5e",
        "66aae991d473b531913bcfc413615846391b0e621d700dc922427ddd6ff15dd3",
        "6791560db8c3880f9ccb6ac7072adf1e22939b7c6a373d23a54f1e0e3019df2f",
        "e84efba53571ac60dc6a0273698ffc6305f3d6d3b4fb763b5df65ed8e67ef019",
        "b26f7ef4e89d7043cdc00a5a3a14d1f3785e685d540d2a60b60defda958ac810",
        "49f218f19cd69b879acffdab8e83b491e774bacaf6f54cb4ffc6c6d7ad4dfe91",
        "118792fe0ab4f2ae255be16867cf7dc89db929588292602d3dff521f2d5a4a5c",
        "84e2a54c9dc5810ae270d747f590bd762b856615e5c6e37c09164b4fef0d0338",
        "b02ed8c0685c232e97944d6744a70ae33e2c7c327019bd2a0a3e0276898558ce",
        "d0e33055cf1395366a3dde85de40f205b4e1f99972e3cbd7ca4fe20c95e60b9d",
        "cdee8cfb844f907ae06681f4e228d20eb3d467962083ba9b348d57d19544f122",
        "5231aa38e9cc4aafce719a2440dad77c1627ac158bed793be111d4c9a154d5b7",
        "39fa66bcf601997f16d9b73d0c2a35a3a5c99d5a8f134fd4928dbd37600b6df4",
        "f540f0beadf326e7db4cd7b166461bf772254ea27dc78cc18a1acb6c0f2027b2",
    },
    "source.method.name": {
        "loadsharedruntimedex",
        "oncreatedialog",
        "onresume",
        "onwindowfocuschanged",
        "onoptionsmenuclosed",
        "oncreatepanelmenu",
        "init",
        "onbackpressed",
        "ontouchevent",
        "onattachedtowindow",
        "oncreatepanelview",
        "launchmarketplaceforair",
        "loadcaptiveruntimeclasses",
        "killself",
        "oncontentchanged",
        "onmenuitemselected",
        "onmenuopened",
        "oncreate",
        "onpostresume",
        "onkeymultiple",
        "oncancel",
        "oncreateview",
        "onlowmemory",
        "launchairservice",
        "onwindowattributeschanged",
        "access$100",
        "oncreatecontextmenu",
        "oncreatedescription",
        "ondetachedfromwindow",
        "getid",
        "isruntimeinstalled",
        "onkeylongpress",
        "ondestroy",
        "invokewrapperoncreate",
        "onpause",
        "showdialog",
        "onpreparedialog",
        "access$000",
        "onchildtitlechanged",
        "onactivityresult",
        "oncontextmenuclosed",
        "isruntimeonexternalstorage",
        "onsearchrequested",
        "main",
        "access$300",
        "onoptionsitemselected",
        "createactivitywrapper",
        "onuserleavehint",
        "oncreatethumbnail",
        "onpreparepanel",
        "access$200",
        "onserviceconnected",
        "showruntimeonexternalstoragedialog",
        "onkeydown",
        "onstart",
        "onconfigurationchanged",
        "onretainnonconfigurationinstance",
        "onpostcreate",
        "onrestoreinstancestate",
        "ontrackballevent",
        "onclick",
        "finishactivityfromchild",
        "onrestart",
        "broadcastintent",
        "oncreateoptionsmenu",
        "onsaveinstancestate",
        "onservicedisconnected",
        "finishfromchild",
        "onprepareoptionsmenu",
        "onapplythemeresource",
        "ontitlechanged",
        "onuserinteraction",
        "<init>",
        "oncontextitemselected",
        "onnewintent",
        "<clinit>",
        "access$500",
        "invokemethod",
        "onkeyup",
        "gatherresourceinfo",
        "showruntimenotinstalleddialog",
        "access$400",
        "onpanelclosed",
        "onstop",
    },
    "source.format": {"dex"},
    "source.method.path": {
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onactivityresult",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onattachedtowindow",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$400",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showruntimenotinstalleddialog",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onbackpressed",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncontextmenuclosed",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$000",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onkeyup",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->launchmarketplaceforair",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onsaveinstancestate",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatedialog",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showruntimeonexternalstoragedialog",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onuserinteraction",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onstart",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onkeylongpress",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onrestart",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onoptionsitemselected",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->launchairservice",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$200",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->isruntimeinstalled",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/getversioncode;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onoptionsmenuclosed",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->createactivitywrapper",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->isruntimeonexternalstorage",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpreparedialog",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/r$string;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onretainnonconfigurationinstance",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$500",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->finishfromchild",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncontentchanged",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onprepareoptionsmenu",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$100",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onkeydown",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpanelclosed",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreateoptionsmenu",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;->onservicedisconnected",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onmenuopened",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatecontextmenu",
        "lcom/adobe/air/resourceidmap;->init",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->finishactivityfromchild",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$300",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->invokemethod",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpause",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onresume",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;-><clinit>",
        "lair/jp/co/studio/arcana/regwoosh/getversioncode;->main",
        "lair/jp/co/studio/arcana/regwoosh/r$style;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onchildtitlechanged",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;->onserviceconnected",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->invokewrapperoncreate",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onkeymultiple",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreate",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->ondetachedfromwindow",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpostresume",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->ontrackballevent",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->ontouchevent",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showdialog",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatepanelmenu",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->broadcastintent",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncontextitemselected",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatethumbnail",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatedescription",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;->onclick",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;->onclick",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onmenuitemselected",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->ontitlechanged",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onnewintent",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->loadsharedruntimedex",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;->oncancel",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpreparepanel",
        "lcom/adobe/air/resourceidmap;->getid",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onrestoreinstancestate",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->ondestroy",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onsearchrequested",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onuserleavehint",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onwindowfocuschanged",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onpostcreate",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreateview",
        "lair/jp/co/studio/arcana/regwoosh/r$attr;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/r$drawable;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onconfigurationchanged",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onlowmemory",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onstop",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->loadcaptiveruntimeclasses",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->killself",
        "lcom/adobe/air/resourceidmap;-><init>",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onapplythemeresource",
        "lair/jp/co/studio/arcana/regwoosh/r;-><init>",
        "lcom/adobe/air/resourceidmap;->gatherresourceinfo",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->oncreatepanelview",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->onwindowattributeschanged",
    },
    "source.class.name": {
        "r$attr",
        "r$string",
        "appentry$1",
        "appentry$3",
        "appentry$2",
        "appentry$4",
        "appentry",
        "r$drawable",
        "r",
        "r$raw",
        "getversioncode",
        "resourceidmap",
        "r$style",
    },
    "source.string": {
        "",
        "setaction",
        "attrs",
        "1.0.1",
        "resource_button_install",
        "init",
        "addflags",
        "access$000",
        "onactivityresult",
        "ljava/lang/class;",
        "string",
        "marketplaceurl",
        "landroid/content/dialoginterface$onclicklistener;",
        "ljava/lang/class",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;",
        "metadata",
        "createpackagecontext",
        "println",
        "oncancel",
        "ljava/util/hashtable",
        "rsckey",
        "launchmarketplaceforair",
        "landroid/content/res/resources$notfoundexception;",
        "append",
        "vli",
        "onlowmemory",
        "getfilesdir",
        "vlz",
        "oncreatepanelmenu",
        "method",
        "isruntimeonexternalstorage",
        "zl",
        "com.adobe.air.androidactivitywrapper",
        "v",
        "childactivity",
        "string.button_exit",
        "clsname",
        "ldalvik/annotation/enclosingclass;",
        "oncreatedescription",
        "<clinit>",
        "menu",
        "onkeyup",
        "debugger",
        "startuptime1",
        "getpackageinfo",
        "ljava/lang/illegalaccessexception;",
        "contains",
        "getdeclaredfields",
        "showdialog",
        "ljava/lang/system;",
        "extraargs",
        "onkeydown",
        "llll",
        "v",
        "f",
        "viil",
        "vllll",
        "invokemethod",
        "resourceclass",
        "onoptionsmenuclosed",
        "sandroidactivitywrapperclass",
        "r.java",
        "substring",
        "killprocess",
        "onstop",
        "landroid/content/context;",
        "oncreateview",
        "ll",
        "lj",
        "li",
        "isruntimeinstalled",
        "landroid/view/menu;",
        "landroid/r$id;",
        "onuserinteraction",
        "lz",
        "gatherresourceinfo",
        "onoptionsitemselected",
        "oncontextmenuclosed",
        "lair/jp/co/studio/arcana/regwoosh/r$style;",
        "ljava/lang/classnotfoundexception;",
        "onmenuopened",
        "market://details?id=",
        "data",
        "oncreateoptionsmenu",
        "[ljava/lang/string;",
        "onuserleavehint",
        "retval",
        "com.adobe.air.airserviceaction",
        "ljava/lang/stringbuilder;",
        "text_install_runtime",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;",
        "gettime",
        "onattachedtowindow",
        "class not found:  %s%n%n",
        "xmlpath",
        "resource_button_exit",
        "ljava/util/hashtable;",
        "ljava/lang/reflect/field;",
        "style",
        "resourceids",
        "oncreatepanelview",
        "resourcestring",
        "onchildtitlechanged",
        "main",
        "<",
        "cls",
        "access$300",
        "parseuri",
        "l",
        "zlli",
        "onrestart",
        "zil",
        "nfe",
        "name",
        "onprepareoptionsmenu",
        "ldalvik/annotation/memberclasses;",
        "vil",
        "[ljava/lang/class;",
        "landroid/content/serviceconnection;",
        "containskey",
        "landroid/content/activitynotfoundexception;",
        "onwindowfocuschanged",
        "resource_title_adobe_air",
        "event",
        "out",
        "canvas",
        "item",
        "onkeylongpress",
        "ondestroy",
        "requestcode",
        "onpause",
        "onpostcreate",
        "landroid/graphics/bitmap;",
        "negativebuttonid",
        "args",
        "button_install",
        "put",
        "onretainnonconfigurationinstance",
        "onapplythemeresource",
        "ljava/lang/classloader;",
        "oncontextitemselected",
        "onnewintent",
        "ljava/lang/class<*>;",
        "first",
        "text_runtime_on_external_storage",
        ">;",
        "landroid/content/res/resources$theme;",
        "valueof",
        "landroid/content/pm/packagemanager$namenotfoundexception;",
        "loadcaptiveruntimeclasses",
        "ljava/lang/exception;",
        "metadata",
        "sandroidactivitywrapper",
        "isadl",
        "service",
        "ljava/lang/integer;",
        "i$",
        "onkeymultiple",
        "params",
        ">;)v",
        "landroid/view/contextmenu$contextmenuinfo;",
        "log_tag",
        "setnegativebutton",
        "ljava/io/file;",
        "x0",
        "x1",
        "landroid/view/windowmanager$layoutparams;",
        "mypid",
        "landroid/content/componentname;",
        "ontitlechanged",
        "illegalargumentexception",
        "oncontentchanged",
        "r",
        "access$500",
        "resource_text_runtime_required",
        "lair/jp/co/studio/arcana/regwoosh/getversioncode;",
        "landroid/view/motionevent;",
        "getstring",
        ">;>;",
        "ldalvik/annotation/enclosingmethod;",
        "setoncancellistener",
        "raw",
        "string.text_install_runtime",
        "bindservice",
        "startactivity",
        "getid",
        "debuginfo",
        "sdloader",
        "which",
        "ljava/lang/boolean;",
        "s_resourcemap",
        "ljava/util/date;",
        "oncreatethumbnail",
        "onpreparepanel",
        "onstart",
        "onconfigurationchanged",
        "landroid/app/activity;",
        "outbitmap",
        "vll",
        "indexofdollarsign",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;",
        "landroid/content/intent;",
        "app_name",
        "show",
        "text",
        "getapplicationinfo",
        "landroid/graphics/canvas;",
        "getcomponentname",
        "launchairservice",
        "title",
        "(",
        "landroid/view/keyevent;",
        "lil",
        "theme",
        "ldalvik/annotation/signature;",
        "invoke",
        "get",
        "illegalaccessexception",
        "aintent",
        "landroid/util/log;",
        "positivebuttonid",
        "landroid/app/alertdialog;",
        "finishfromchild",
        "fields",
        "landroid/content/pm/applicationinfo;",
        "lair/jp/co/studio/arcana/regwoosh/r$attr;",
        "keycode",
        "view",
        "onresume",
        "resultcode",
        "onwindowattributeschanged",
        "getname",
        "landroid/content/dialoginterface;",
        "tostring",
        "landroid/view/view;",
        "mp_warning_32x32_n",
        "access$200",
        "showruntimeonexternalstoragedialog",
        "vill",
        "ontouchevent",
        "-nodebug",
        "lair/jp/co/studio/arcana/regwoosh/r$string;",
        "getpackagemanager",
        "getabsolutepath",
        "pkgmgr",
        "landroid/view/menuitem;",
        "resourceidmap.java",
        "context",
        "getclasses",
        "string.title_adobe_air",
        "con",
        "oncreatedialog",
        "com.adobe.air",
        "methodcreateandroidactivitywrapper",
        "color",
        "ill",
        "string.text_runtime_on_external_storage",
        "landroid/os/bundle;",
        "landroid/content/pm/packagemanager;",
        "oncreate",
        "unbindservice",
        "getmethod",
        "ljava/lang/reflect/method;",
        "app_version",
        "getactivityinfo",
        "getint",
        "child",
        "string.text_runtime_required",
        "landroid/app/alertdialog$builder;",
        "runtime_package_id",
        "value",
        "drawable",
        "ljava/lang/illegalargumentexception;",
        "type",
        "[ljava/lang/reflect/field;",
        "string.button_install",
        "repeatcount",
        "ii",
        "landroid/content/pm/activityinfo;",
        "ldalvik/annotation/throws;",
        "setclassname",
        "onpostresume",
        "id",
        "conn",
        "lair/jp/co/studio/arcana/regwoosh/r;",
        "vilii",
        "did not add duplicate resource key %s",
        "millis",
        "savedinstancestate",
        "access$100",
        "createandroidactivitywrapper",
        "theme_noshadow",
        "clss",
        "[ljava/lang/class<*>;",
        "i",
        "vi",
        "lcom/adobe/air/resourceidmap;",
        "setmessage",
        "vl",
        "m_resourceids",
        "ii",
        "action",
        "<*>;)v",
        "il",
        "vz",
        "broadcastintent",
        "sruntimeclassesloaded",
        "newconfig",
        "landroid/view/contextmenu;",
        "i",
        "ljava/lang/charsequence;",
        "flags",
        "access$400",
        "resource_class",
        "hasfocus",
        "onbackpressed",
        "ldalvik/annotation/innerclass;",
        "<*>;",
        "titleid",
        "this$0",
        "landroid/os/ibinder;",
        "booleanvalue",
        "lair/jp/co/studio/arcana/regwoosh/appentry;",
        "featureid",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;",
        "landroid/os/process;",
        "onsearchrequested",
        "format",
        "airdownloadurl",
        "[ljava/lang/object;",
        "finishactivityfromchild",
        "ziil",
        "resid",
        "landroid/app/dialog;",
        "t",
        "onserviceconnected",
        "onpanelclosed",
        "hascaptiveruntime",
        "zll",
        "intern",
        "onmenuitemselected",
        "com.adobe.air.airservice",
        "landroid/content/pm/packageinfo;",
        "internedresourcestring",
        "ondetachedfromwindow",
        "outstate",
        "lli",
        "invokewrapperoncreate",
        "exit",
        "lll",
        "rgba8888",
        "ljava/net/urisyntaxexception;",
        "text_runtime_required",
        "air.jp.co.studio.arcana.regwoosh.r",
        "ldalvik/system/dexclassloader;",
        "onclick",
        "rootdirectory",
        "lair/jp/co/studio/arcana/regwoosh/r$drawable;",
        "dialog",
        "landroid/util/attributeset;",
        "zill",
        "setpositivebutton",
        "menuinfo",
        "appinfo",
        "button_exit",
        "accessflags",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;",
        "onpreparedialog",
        "vlll",
        ":",
        "loadclass",
        "j",
        "title_adobe_air",
        "intvalue",
        "forname",
        "killself",
        "onservicedisconnected",
        "z",
        "info",
        "attr",
        "ljava/lang/string;",
        "<init>",
        "vliz",
        "loadsharedruntimedex",
        "icon",
        "len$",
        "settitle",
        "%s.%s",
        "landroid/content/res/configuration;",
        "appentry.java",
        "landroid/content/dialoginterface$oncancellistener;",
        "showruntimenotinstalleddialog",
        "getversioncode.java",
        "lastindexof",
        "createactivitywrapper",
        "ljava/io/printstream;",
        "android.intent.action.view",
        "getclassloader",
        "appentry",
        "onrestoreinstancestate",
        "intent",
        "ontrackballevent",
        "ljava/lang/object;",
        "ljava/util/hashtable<ljava/lang/string;ljava/lang/integer;>;",
        "arr$",
        "e",
        "isdebuggermode",
        "oncreatecontextmenu",
        "alertdialogbuilder",
        "onsaveinstancestate",
    },
    "source.class.super": {
        "a",
        "o",
        "c",
        "b",
        "e",
        "d",
        "g",
        "i",
        "j",
        "l",
        "/",
        "l",
        "p",
        "r",
        "a",
        "o",
        "v",
        "y",
        ";",
        "n",
        "t",
    },
    "source.class.package": {"com/adobe/air", "air/jp/co/studio/arcana/regwoosh"},
    "source.class.path": {
        "lair/jp/co/studio/arcana/regwoosh/r$string;",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;",
        "lair/jp/co/studio/arcana/regwoosh/r;",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;",
        "lcom/adobe/air/resourceidmap;",
        "lair/jp/co/studio/arcana/regwoosh/getversioncode;",
        "lair/jp/co/studio/arcana/regwoosh/r$style;",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;",
        "lair/jp/co/studio/arcana/regwoosh/r$attr;",
        "lair/jp/co/studio/arcana/regwoosh/r$drawable;",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;",
    },
    "source.invoke": {
        "landroid/app/activity;->oncreatecontextmenu(landroid/view/contextmenu; landroid/view/view; landroid/view/contextmenu$contextmenuinfo;)v",
        "landroid/app/activity;->onkeymultiple(i i landroid/view/keyevent;)z",
        "landroid/app/activity;->oncreatepanelmenu(i landroid/view/menu;)z",
        "landroid/content/intent;->setaction(ljava/lang/string;)landroid/content/intent;",
        "landroid/content/context;->getclassloader()ljava/lang/classloader;",
        "landroid/app/activity;->finishactivityfromchild(landroid/app/activity; i)v",
        "ljava/lang/stringbuilder;-><init>()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->launchairservice()v",
        "landroid/app/activity;->onpanelclosed(i landroid/view/menu;)v",
        "landroid/app/activity;->onrestoreinstancestate(landroid/os/bundle;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->invokemethod(ljava/lang/reflect/method; [ljava/lang/object;)ljava/lang/object;",
        "landroid/app/activity;->oncontextmenuclosed(landroid/view/menu;)v",
        "ljava/util/hashtable;->put(ljava/lang/object; ljava/lang/object;)ljava/lang/object;",
        "landroid/app/alertdialog$builder;->setmessage(ljava/lang/charsequence;)landroid/app/alertdialog$builder;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->startactivity(landroid/content/intent;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->getcomponentname()landroid/content/componentname;",
        "landroid/app/activity;->onmenuopened(i landroid/view/menu;)z",
        "landroid/app/activity;->onsaveinstancestate(landroid/os/bundle;)v",
        "landroid/app/activity;->oncontextitemselected(landroid/view/menuitem;)z",
        "landroid/app/activity;->onbackpressed()v",
        "ljava/lang/illegalargumentexception;-><init>()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$200(lair/jp/co/studio/arcana/regwoosh/appentry; z)v",
        "ldalvik/system/dexclassloader;->loadclass(ljava/lang/string;)ljava/lang/class;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$400(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "landroid/util/log;->i(ljava/lang/string; ljava/lang/string;)i",
        "landroid/app/activity;->onmenuitemselected(i landroid/view/menuitem;)z",
        "ljava/lang/object;-><init>()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->loadsharedruntimedex()v",
        "landroid/os/process;->killprocess(i)v",
        "landroid/content/intent;->parseuri(ljava/lang/string; i)landroid/content/intent;",
        "landroid/app/activity;->ondetachedfromwindow()v",
        "ljava/io/file;->getabsolutepath()ljava/lang/string;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->broadcastintent(ljava/lang/string; ljava/lang/string;)v",
        "landroid/app/activity;->onpreparepanel(i landroid/view/view; landroid/view/menu;)z",
        "ljava/lang/string;->intern()ljava/lang/string;",
        "ljava/util/hashtable;->get(ljava/lang/object;)ljava/lang/object;",
        "landroid/app/activity;-><init>()v",
        "landroid/app/activity;->onuserinteraction()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$300()z",
        "ljava/lang/boolean;->tostring()ljava/lang/string;",
        "landroid/content/res/resources$notfoundexception;-><init>(ljava/lang/string;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->bindservice(landroid/content/intent; landroid/content/serviceconnection; i)z",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->invokewrapperoncreate()v",
        "lcom/adobe/air/resourceidmap;->gatherresourceinfo(ljava/lang/class; ljava/util/hashtable;)v",
        "landroid/app/activity;->onuserleavehint()v",
        "ljava/lang/string;->format(ljava/lang/string; [ljava/lang/object;)ljava/lang/string;",
        "landroid/app/alertdialog$builder;-><init>(landroid/content/context;)v",
        "ljava/lang/class;->getdeclaredfields()[ljava/lang/reflect/field;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showruntimenotinstalleddialog()v",
        "ljava/io/printstream;->format(ljava/lang/string; [ljava/lang/object;)ljava/io/printstream;",
        "ljava/io/printstream;->println(ljava/lang/string;)v",
        "landroid/app/activity;->oncreate(landroid/os/bundle;)v",
        "landroid/app/activity;->ontrackballevent(landroid/view/motionevent;)z",
        "landroid/app/activity;->onattachedtowindow()v",
        "landroid/app/activity;->onstop()v",
        "ljava/lang/reflect/field;->getint(ljava/lang/object;)i",
        "landroid/app/activity;->onchildtitlechanged(landroid/app/activity; ljava/lang/charsequence;)v",
        "ljava/lang/string;->lastindexof(i)i",
        "landroid/app/activity;->onpause()v",
        "landroid/content/intent;->setclassname(ljava/lang/string; ljava/lang/string;)landroid/content/intent;",
        "ljava/util/date;->gettime()j",
        "landroid/app/activity;->ondestroy()v",
        "landroid/app/activity;->onretainnonconfigurationinstance()ljava/lang/object;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->killself()v",
        "ljava/util/hashtable;->containskey(ljava/lang/object;)z",
        "landroid/app/activity;->oncreatedescription()ljava/lang/charsequence;",
        "landroid/app/activity;->onwindowfocuschanged(z)v",
        "ljava/util/hashtable;-><init>()v",
        "landroid/app/alertdialog$builder;->settitle(i)landroid/app/alertdialog$builder;",
        "lcom/adobe/air/resourceidmap;->init(ljava/lang/class;)v",
        "landroid/app/activity;->onrestart()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->isruntimeonexternalstorage()z",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$100(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "landroid/app/activity;->onkeylongpress(i landroid/view/keyevent;)z",
        "landroid/app/activity;->onstart()v",
        "ljava/lang/system;->exit(i)v",
        "landroid/app/activity;->oncontentchanged()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;-><init>(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "ljava/lang/class;->getclasses()[ljava/lang/class;",
        "ljava/lang/boolean;-><init>(z)v",
        "landroid/app/activity;->onoptionsitemselected(landroid/view/menuitem;)z",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showdialog(i ljava/lang/string; i i)v",
        "landroid/app/activity;->onsearchrequested()z",
        "landroid/app/activity;->onoptionsmenuclosed(landroid/view/menu;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->getpackagemanager()landroid/content/pm/packagemanager;",
        "landroid/app/activity;->ontitlechanged(ljava/lang/charsequence; i)v",
        "landroid/app/activity;->onconfigurationchanged(landroid/content/res/configuration;)v",
        "ljava/util/date;-><init>()v",
        "landroid/app/activity;->oncreateview(ljava/lang/string; landroid/content/context; landroid/util/attributeset;)landroid/view/view;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->launchmarketplaceforair()v",
        "landroid/app/activity;->onpostresume()v",
        "ljava/util/hashtable;->contains(ljava/lang/object;)z",
        "landroid/app/activity;->oncreatedialog(i landroid/os/bundle;)landroid/app/dialog;",
        "ljava/lang/string;->substring(i)ljava/lang/string;",
        "landroid/content/intent;-><init>(ljava/lang/string;)v",
        "landroid/app/activity;->onpostcreate(landroid/os/bundle;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->getfilesdir()ljava/io/file;",
        "ldalvik/system/dexclassloader;-><init>(ljava/lang/string; ljava/lang/string; ljava/lang/string; ljava/lang/classloader;)v",
        "landroid/app/activity;->oncreateoptionsmenu(landroid/view/menu;)z",
        "landroid/app/activity;->oncreatethumbnail(landroid/graphics/bitmap; landroid/graphics/canvas;)z",
        "landroid/app/alertdialog$builder;->setnegativebutton(i landroid/content/dialoginterface$onclicklistener;)landroid/app/alertdialog$builder;",
        "landroid/app/activity;->onnewintent(landroid/content/intent;)v",
        "landroid/content/pm/packagemanager;->getpackageinfo(ljava/lang/string; i)landroid/content/pm/packageinfo;",
        "ljava/lang/class;->getname()ljava/lang/string;",
        "landroid/app/activity;->onprepareoptionsmenu(landroid/view/menu;)z",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->createpackagecontext(ljava/lang/string; i)landroid/content/context;",
        "landroid/app/activity;->onwindowattributeschanged(landroid/view/windowmanager$layoutparams;)v",
        "lcom/adobe/air/resourceidmap;-><init>(ljava/lang/string;)v",
        "ljava/lang/integer;->valueof(i)ljava/lang/integer;",
        "lcom/adobe/air/resourceidmap;->getid(ljava/lang/string;)i",
        "landroid/app/activity;->onapplythemeresource(landroid/content/res/resources$theme; i z)v",
        "ljava/lang/class;->getmethod(ljava/lang/string; [ljava/lang/class;)ljava/lang/reflect/method;",
        "landroid/app/activity;->ontouchevent(landroid/view/motionevent;)z",
        "ljava/lang/class;->forname(ljava/lang/string;)ljava/lang/class;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->isruntimeinstalled()z",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;-><init>(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "ljava/lang/stringbuilder;->tostring()ljava/lang/string;",
        "landroid/app/activity;->onpreparedialog(i landroid/app/dialog; landroid/os/bundle;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->showruntimeonexternalstoragedialog()v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->unbindservice(landroid/content/serviceconnection;)v",
        "landroid/content/pm/packagemanager;->getactivityinfo(landroid/content/componentname; i)landroid/content/pm/activityinfo;",
        "ljava/lang/reflect/method;->invoke(ljava/lang/object; [ljava/lang/object;)ljava/lang/object;",
        "landroid/app/activity;->finishfromchild(landroid/app/activity;)v",
        "landroid/app/activity;->onpreparedialog(i landroid/app/dialog;)v",
        "landroid/app/activity;->onkeyup(i landroid/view/keyevent;)z",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;-><init>(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "landroid/app/alertdialog$builder;->setoncancellistener(landroid/content/dialoginterface$oncancellistener;)landroid/app/alertdialog$builder;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->createactivitywrapper(z)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$500()v",
        "ljava/lang/reflect/field;->getname()ljava/lang/string;",
        "landroid/os/bundle;->get(ljava/lang/string;)ljava/lang/object;",
        "landroid/app/activity;->oncreatepanelview(i)landroid/view/view;",
        "ljava/lang/stringbuilder;->append(j)ljava/lang/stringbuilder;",
        "landroid/app/activity;->oncreatedialog(i)landroid/app/dialog;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->loadcaptiveruntimeclasses()z",
        "ljava/lang/stringbuilder;->append(ljava/lang/string;)ljava/lang/stringbuilder;",
        "ljava/lang/boolean;->booleanvalue()z",
        "landroid/app/alertdialog$builder;->setpositivebutton(i landroid/content/dialoginterface$onclicklistener;)landroid/app/alertdialog$builder;",
        "landroid/app/alertdialog$builder;->show()landroid/app/alertdialog;",
        "landroid/content/pm/packagemanager;->getapplicationinfo(ljava/lang/string; i)landroid/content/pm/applicationinfo;",
        "ljava/lang/integer;->intvalue()i",
        "landroid/content/intent;->addflags(i)landroid/content/intent;",
        "ljava/lang/boolean;->valueof(z)ljava/lang/boolean;",
        "landroid/app/activity;->onresume()v",
        "landroid/os/process;->mypid()i",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;-><init>(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->getstring(i)ljava/lang/string;",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->access$000(lair/jp/co/studio/arcana/regwoosh/appentry;)v",
        "landroid/app/activity;->onkeydown(i landroid/view/keyevent;)z",
    },
    "source.field.name": {
        "text_runtime_on_external_storage",
        "text_install_runtime",
        "debugger",
        "resource_class",
        "sandroidactivitywrapperclass",
        "resource_button_exit",
        "app_name",
        "button_exit",
        "button_install",
        "resource_button_install",
        "log_tag",
        "sdloader",
        "rgba8888",
        "app_version",
        "theme_noshadow",
        "s_resourcemap",
        "mp_warning_32x32_n",
        "debuginfo",
        "text_runtime_required",
        "this$0",
        "title_adobe_air",
        "m_resourceids",
        "sandroidactivitywrapper",
        "sruntimeclassesloaded",
        "icon",
        "runtime_package_id",
        "resource_title_adobe_air",
        "resource_text_runtime_required",
    },
    "source.debug": {False},
    "source.field.path": {
        "lair/jp/co/studio/arcana/regwoosh/r$drawable;->icon",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->resource_button_exit",
        "lair/jp/co/studio/arcana/regwoosh/appentry$1;->this$0",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->runtime_package_id",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->text_runtime_required",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->text_install_runtime",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->sdloader",
        "lcom/adobe/air/resourceidmap;->s_resourcemap",
        "lair/jp/co/studio/arcana/regwoosh/appentry$3;->this$0",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->title_adobe_air",
        "lair/jp/co/studio/arcana/regwoosh/r$style;->theme_noshadow",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;->debuginfo",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;->rgba8888",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->resource_title_adobe_air",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->button_install",
        "lair/jp/co/studio/arcana/regwoosh/r$raw;->debugger",
        "lair/jp/co/studio/arcana/regwoosh/r$drawable;->mp_warning_32x32_n",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->resource_button_install",
        "lcom/adobe/air/resourceidmap;->m_resourceids",
        "lair/jp/co/studio/arcana/regwoosh/appentry$4;->this$0",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->text_runtime_on_external_storage",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->resource_text_runtime_required",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->sandroidactivitywrapper",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->app_version",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->log_tag",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->button_exit",
        "lair/jp/co/studio/arcana/regwoosh/r$string;->app_name",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->sandroidactivitywrapperclass",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->resource_class",
        "lair/jp/co/studio/arcana/regwoosh/appentry;->sruntimeclassesloaded",
        "lair/jp/co/studio/arcana/regwoosh/appentry$2;->this$0",
    },
}

CERTIFICATE = {
    "certificate.owner": {
        'cn="studio arcana co., ltd.", ou="studio arcana co., ltd.", o="studio arcana co., ltd.", c=jp'
    },
    "certificate.signature": {
        "37:fe:73:1f:31:95:ef:ba:e5:84:cd:f7:d2:ad:3a:ad:58:b5:6a:1d:9d:53:85:f3:91:10:f0:bc:73:d7:fb:c1"
    },
    "certificate.issuer": {
        'cn="studio arcana co., ltd.", ou="studio arcana co., ltd.", o="studio arcana co., ltd.", c=jp'
    },
}

FILE = {
    "file.sha256": {
        "0fc4b18d5b5a482fabb7d9444b62e664d2431a1a333b415d3f7ef307cd1117f9",
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "c30897a1755bcddbc9ce07c89ff136805c43680a24c29975fd3644a716e83868",
        "b369a4aee8471433990ca2ed4b284fa86fee56810ab89146e2f550912e932a9f",
        "56b5cf0f71dcfef6c38cc18310f082af839aa3799a2dc3b051099c0d3cf95d4a",
        "4a9cd203dde2813c5111c058c9e789d9c5be3d49cdd72ee0cb8cc361d9beef52",
        "0903dedd82f103a8396748634b2765962a938df93772713503d4b77182246d12",
        "df0ced7a918aa3649015a76e5b85756c1312b9efe0cb665ec4074799aebcb9e1",
        "735191e7635b28eabb961ab3e666ecbef562d6363a420dac835c3be730963657",
        "93c948dade3ee6720ee848cbf551bd7c219c0178afe60df6d63a1f52ba9374c3",
        "a62230fabbbfe589737ab9059f82b96ec19fbb1d426fb7bb3c7d64742a7a0555",
        "3fbd3ae53e22bd3f7c6ae6dffb253bd83328efed6e4a2f4f11da1d23ea688629",
        "01460e0cb9a3f7387169bd6dfcc6776851f6e27c7b03c1eea94f8583881a4a8d",
        "1451806541d0959b0e6a550e9f95718937031ff710dd57b131474af9d9b8875b",
        "b4f6d5f6e936aef0fbde5478ad8cd2d40808f3cea2ab8e209cc5a3649614076d",
        "016819895f6b77d247e7d99f7373e12b5228cf7d413dab1fb867d88634f56541",
        "6e0d934f5d3e5f3da418ff2fa2573aab98ed175d88c4329c3d139c91a36b9cbf",
        "89c6c4cee632998a1b2dd52bc200d00c6dd3f512234a0de0c0bb4ae8f84ddd1c",
    },
    "file.path": {
        "resources.arsc",
        "res/drawable-ldpi/icon.png",
        "assets/default.png",
        "meta-inf/manifest.mf",
        "assets/sound/test02lowcut.mp3",
        "lib/armeabi-v7a/libnativeabi.so",
        "res/raw/debuginfo",
        "res/drawable-mdpi/icon.png",
        "assets/regwoosh.swf",
        "res/drawable/mp_warning_32x32_n.png",
        "meta-inf/cert.rsa",
        "assets/icons/android/icon-48.png",
        "res/drawable-hdpi/icon.png",
        "assets/default-568h@2x.png",
        "assets/default@2x.png",
        "res/raw/rgba8888",
        "classes.dex",
        "assets/icons/android/icon-72.png",
        "androidmanifest.xml",
        "assets/icons/android/icon-36.png",
        "meta-inf/cert.sf",
        "assets/meta-inf/air/application.xml",
    },
    "file.name": {
        "resources.arsc",
        "default.png",
        "cert.sf",
        "mp_warning_32x32_n.png",
        "debuginfo",
        "classes.dex",
        "default@2x.png",
        "application.xml",
        "rgba8888",
        "androidmanifest.xml",
        "icon-36.png",
        "regwoosh.swf",
        "icon.png",
        "libnativeabi.so",
        "icon-48.png",
        "icon-72.png",
        "manifest.mf",
        "cert.rsa",
        "test02lowcut.mp3",
        "default-568h@2x.png",
    },
}


MANIFEST = {
    "manifest.activity": {".appentry"},
    "manifest.minsdk": {8},
    "manifest.maxsdk": {None},
    "manifest.metakey": {
        "initialcontent",
        "uniqueappversionid",
        "fullscreen",
        "autoorients",
        "aspectratio",
        "namespaceversion",
    },
    "manifest.vercode": {1000001},
    "manifest.action": {"android.intent.action.main"},
    "manifest.vername": {"1.0.1"},
    "manifest.metaval": {
        "regwoosh.swf",
        "9132dfcd-4c1b-45dc-81a7-d1181f81e14b",
        "false",
        "false",
        "portrait",
        "3.400000",
    },
    "manifest.tarsdk": {14},
    "manifest.category": {"android.intent.category.launcher"},
    "manifest.permission": {
        "android.permission.read_phone_state",
        "android.permission.write_external_storage",
        "android.permission.internet",
    },
}

RESOURCE = {
    "resource.language": {"default", "ja"},
    "resource.package": {u"air.jp.co.studio.arcana.regwoosh"},
    "resource.string": {
        u"",
        u"regwoosh",
        u"to continue, either install adobe air on this device or exit this application and mount the sd card containing adobe air before re-launching.",
        u"this application requires adobe air.\n\n",
        u"adobe air",
        u" adobe air  adobe air  sd ",
        u"adobe air \n\n",
        u" adobe air ",
        u"exit",
        u"install",
        u"app_version",
        u"to continue, install adobe air on this device.",
    },
    "resource.entry": {
        u"text_runtime_on_external_storage",
        u"button_install",
        u"app_version",
        u"mp_warning_32x32_n",
        u"app_name",
        u"debuginfo",
        u"text_runtime_required",
        u"title_adobe_air",
        u"button_exit",
        u"text_install_runtime",
        u"rgba8888",
        u"icon",
        u"theme.noshadow",
        u"debugger",
    },
}

APK = {}

APK.update(FILE)
APK.update(SOURCE)
APK.update(MANIFEST)
APK.update(RESOURCE)
APK.update(CERTIFICATE)
