#  -*- coding: utf-8 -*-

APKWEB = {
    "sha256": "0000230ae0799eaa963f0ae5337a0e6e1ac32acf1fa4e3c5fa7783cbae2efe77",
    "android_jscIsDetected": 0,
    "appcelerator.titaniumIsDetected": 0,
    "cordovaIsDetected": 0,
    "phonegapIsDetected": 0,
    "rhomobileIsDetected": 0,
    "isHybrid": 0,
    "nbCSS": 0,
    "nbHTML": 0,
    "nbJs": 0,
    "nbTotalandroidInstructions": 0,
    "nbTotalandroidInvokes": 0,
    "nbTotalhybridInstructions": 0,
    "nbTotalhybridInvokes": 0,
    "nbTotalotherInstructions": 2258,
    "nbTotalotherInvokes": 2258,
    "nbTotalownPackageInstructions": 0,
    "nbTotalownPackageInvokes": 0,
    "nbandroidClasses": 0,
    "nbandroidMethods": 0,
    "nbhybridClasses": 0,
    "nbhybridMethods": 0,
    "nbhybridWebviewCalls": 0,
    "nbnonHybridWebviewCalls": 0,
    "nbotherClasses": 13,
    "nbotherMethods": 210,
    "nbownPackageClasses": 0,
    "nbownPackageMethods": 0,
    "sizeCSS": 0,
    "sizeHTML": 0,
    "sizeJs": 0,
    "list_dangerous_permissions": [
        "android.permission.write_external_storage",
        "android.permission.read_phone_state",
    ],
}
