# -*- coding: utf-8 -*-
"""Constants about the Android platform."""

# FROM: https://developer.android.com/reference/packages.html
## - some packages are folded to their parent
## e.g. android.graphics.fonts -> android.graphics

## - some classes have been distinguished
## e.g. java.lang.System, java.lang.Runtime

## - support packages should be folded to their reference
## e.g. android.support.preference -> android.preference

## - traversing should be reversed to analyze specific first
## e.g. android.app.admin > android.app

# CONSTANTS

# order is important to preserve specificity
# e.g. android.content > android.content.pm

PACKAGES = [
    "android",
    "android.accessibilityservice",
    "android.accounts",
    "android.animation",
    "android.annotation",
    "android.app",
    "android.app.admin",
    "android.app.assist",
    "android.app.backup",
    "android.app.job",
    "android.app.usage",
    "android.appwidget",
    "android.bluetooth",
    # "android.bluetooth.le",
    "android.companion",
    "android.content",
    "android.content.pm",
    "android.content.res",
    "android.content.Intent",
    "android.content.IntentFilter",
    "android.database",
    "android.database.sqlite",
    "android.databinding",
    "android.drm",
    "android.gesture",
    "android.graphics",
    # "android.graphics.drawable",
    # "android.graphics.drawable.shapes",
    # "android.graphics.fonts",
    # "android.graphics.pdf",
    "android.hardware",
    "android.hardware.camera2",
    # "android.hardware.camera2.params",
    "android.hardware.display",
    "android.hardware.fingerprint",
    "android.hardware.input",
    "android.hardware.usb",
    "android.icu.lang",
    "android.icu.math",
    "android.icu.text",
    "android.icu.util",
    "android.inputmethodservice",
    "android.location",
    "android.media",
    # "android.media.audiofx",
    # "android.media.browse",
    # "android.media.effect",
    # "android.media.midi",
    # "android.media.projection",
    # "android.media.session",
    # "android.media.tv",
    "android.mtp",
    "android.net",
    "android.net.http",
    "android.net.nsd",
    "android.net.rtp",
    "android.net.sip",
    "android.net.wifi",
    # "android.net.wifi.aware",
    # "android.net.wifi.hotspot2",
    # "android.net.wifi.hotspot2.omadm",
    # "android.net.wifi.hotspot2.pps",
    # "android.net.wifi.p2p",
    # "android.net.wifi.p2p.nsd",
    "android.nfc",
    # "android.nfc.cardemulation",
    # "android.nfc.tech",
    "android.opengl",
    "android.os",
    "android.os.health",
    "android.os.storage",
    "android.preference",
    "android.print",
    # "android.print.pdf",
    "android.printservice",
    "android.provider",
    "android.renderscript",
    "android.sax",
    "android.security",
    "android.security.keystore",
    "android.service.autofill",
    "android.service.carrier",
    "android.service.chooser",
    "android.service.dreams",
    "android.service.media",
    "android.service.notification",
    "android.service.quicksettings",
    "android.service.restrictions",
    "android.service.textservice",
    "android.service.voice",
    "android.service.vr",
    "android.service.wallpaper",
    "android.speech",
    # "android.speech.tts",
    # "android.support.animation",
    # "android.support.annotation",
    # "android.support.app.recommendation",
    # "android.support.compat",
    # "android.support.coreui",
    # "android.support.coreutils",
    # "android.support.customtabs",
    # "android.support.design",
    # "android.support.design.widget",
    # "android.support.dynamicanimation",
    # "android.support.exifinterface",
    # "android.support.fragment",
    # "android.support.graphics.drawable",
    # "android.support.graphics.drawable.animated",
    # "android.support.media",
    # "android.support.media.instantvideo",
    # "android.support.media.instantvideo.preload",
    # "android.support.media.instantvideo.widget",
    # "android.support.media.tv",
    # "android.support.mediacompat",
    # "android.support.multidex",
    # "android.support.percent",
    # "android.support.recommendation",
    # "android.support.transition",
    # "android.support.v13",
    # "android.support.v13.app",
    # "android.support.v13.view",
    # "android.support.v13.view.inputmethod",
    # "android.support.v14.preference",
    # "android.support.v17.leanback",
    # "android.support.v17.leanback.app",
    # "android.support.v17.leanback.database",
    # "android.support.v17.leanback.graphics",
    # "android.support.v17.leanback.media",
    # "android.support.v17.leanback.system",
    # "android.support.v17.leanback.widget",
    # "android.support.v17.leanback.widget.picker",
    # "android.support.v17.preference",
    # "android.support.v4",
    # "android.support.v4.accessibilityservice",
    # "android.support.v4.app",
    # "android.support.v4.content",
    # "android.support.v4.content.pm",
    # "android.support.v4.content.res",
    # "android.support.v4.database",
    # "android.support.v4.graphics",
    # "android.support.v4.graphics.drawable",
    # "android.support.v4.hardware.display",
    # "android.support.v4.hardware.fingerprint",
    # "android.support.v4.math",
    # "android.support.v4.media",
    # "android.support.v4.media.session",
    # "android.support.v4.net",
    # "android.support.v4.os",
    # "android.support.v4.print",
    # "android.support.v4.provider",
    # "android.support.v4.text",
    # "android.support.v4.text.util",
    # "android.support.v4.util",
    # "android.support.v4.view",
    # "android.support.v4.view.accessibility",
    # "android.support.v4.view.animation",
    # "android.support.v4.widget",
    # "android.support.v7.app",
    # "android.support.v7.appcompat",
    # "android.support.v7.cardview",
    # "android.support.v7.content.res",
    # "android.support.v7.graphics",
    # "android.support.v7.graphics.drawable",
    # "android.support.v7.gridlayout",
    # "android.support.v7.media",
    # "android.support.v7.mediarouter",
    # "android.support.v7.palette",
    # "android.support.v7.preference",
    # "android.support.v7.recyclerview",
    # "android.support.v7.util",
    # "android.support.v7.view",
    # "android.support.v7.widget",
    # "android.support.v7.widget.helper",
    # "android.support.v7.widget.util",
    # "android.support.v8.renderscript",
    # "android.support.wearable",
    # "android.support.wearable.view",
    "android.system",
    "android.telecom",
    "android.telephony",
    "android.telephony.cdma",
    "android.telephony.gsm",
    "android.test",
    # "android.test.mock",
    # "android.test.suitebuilder",
    # "android.test.suitebuilder.annotation",
    "android.text",
    # "android.text.format",
    # "android.text.method",
    # "android.text.style",
    # "android.text.util",
    "android.transition",
    "android.util",
    "android.view",
    # "android.view.accessibility",",
    # "android.view.animation",",
    # "android.view.autofill",
    # "android.view.inputmethod",
    # "android.view.textclassifier",
    # "android.view.textservice",
    "android.webkit",
    "android.widget",
    "com.android.internal.backup",
    "com.android.internal.inputmethod",
    "com.android.internal.logging",
    "com.android.internal.os",
    "com.android.internal.statusbar",
    "com.android.internal.widget",
    "com.android.test.runner",
    "dalvik.annotation",
    "dalvik.bytecode",
    "dalvik.system",
    "java.awt.font",
    "java.beans",
    "java.io",
    "java.lang",
    "java.lang.annotation",
    "java.lang.invoke",
    "java.lang.ref",
    "java.lang.reflect",
    "java.lang.System",
    "java.lang.Runtime",
    "java.lang.Process",
    "java.lang.ClassLoader",
    "java.lang.ProcessBuilder",
    "java.math",
    "java.net",
    "java.nio",
    "java.nio.channels",
    # "java.nio.channels.spi",
    "java.nio.charset",
    # "java.nio.charset.spi",
    "java.nio.file",
    # "java.nio.file.attribute",
    # "java.nio.file.spi",
    "java.security",
    "java.security.acl",
    "java.security.cert",
    "java.security.interfaces",
    "java.security.spec",
    "java.sql",
    "java.text",
    "java.time",
    # "java.time.chrono",
    # "java.time.format",
    # "java.time.temporal",
    # "java.time.zone",
    "java.util",
    "java.util.concurrent",
    # "java.util.concurrent.atomic",
    # "java.util.concurrent.locks",
    "java.util.function",
    "java.util.jar",
    "java.util.logging",
    "java.util.prefs",
    "java.util.regex",
    "java.util.stream",
    "java.util.zip",
    "javax.crypto",
    # "javax.crypto.interfaces",
    # "javax.crypto.spec",
    "javax.microedition.khronos.egl",
    "javax.microedition.khronos.opengles",
    "javax.net",
    "javax.net.ssl",
    "javax.security.auth",
    # "javax.security.auth.callback",",
    # "javax.security.auth.login",
    # "javax.security.auth.x500",
    "javax.security.cert",
    "javax.sql",
    "javax.xml",
    # "javax.xml.datatype",",
    # "javax.xml.namespace",
    # "javax.xml.parsers",
    # "javax.xml.transform",
    # "javax.xml.transform.dom",
    # "javax.xml.transform.sax",
    # "javax.xml.transform.stream",
    # "javax.xml.validation",
    # "javax.xml.xpath",
    "junit.framework",
    "junit.runner",
    "org.apache.http.conn",
    "org.apache.http.conn.scheme",
    "org.apache.http.conn.ssl",
    "org.apache.http.params",
    "org.json",
    "org.w3c.dom",
    # "org.w3c.dom.ls",
    "org.xml.sax",
    # "org.xml.sax.ext",
    # "org.xml.sax.helpers",
    "org.xmlpull.v1",
    "org.xmlpull.v1.sax2",
]

# FROM: https://developer.android.com/reference/android/Manifest.permission.html

PERMISSIONS = frozenset(
    [
        "ACCESS_CHECKIN_PROPERTIES",
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "ACCESS_LOCATION_EXTRA_COMMANDS",
        "ACCESS_NETWORK_STATE",
        "ACCESS_NOTIFICATION_POLICY",
        "ACCESS_WIFI_STATE",
        "ACCOUNT_MANAGER",
        "ADD_VOICEMAIL",
        "ALLOCATE_AGGRESSIVE",
        "BATTERY_STATS",
        "BIND_ACCESSIBILITY_SERVICE",
        "BIND_APPWIDGET",
        "BIND_AUTO_FILL",
        "BIND_CARRIER_MESSAGING_SERVICE",
        "BIND_CARRIER_SERVICES",
        "BIND_CHOOSER_TARGET_SERVICE",
        "BIND_CONDITION_PROVIDER_SERVICE",
        "BIND_DEVICE_ADMIN",
        "BIND_DREAM_SERVICE",
        "BIND_INCALL_SERVICE",
        "BIND_INPUT_METHOD",
        "BIND_MIDI_DEVICE_SERVICE",
        "BIND_NFC_SERVICE",
        "BIND_NOTIFICATION_LISTENER_SERVICE",
        "BIND_PRINT_SERVICE",
        "BIND_QUICK_SETTINGS_TILE",
        "BIND_REMOTEVIEWS",
        "BIND_SCREENING_SERVICE",
        "BIND_TELECOM_CONNECTION_SERVICE",
        "BIND_TEXT_SERVICE",
        "BIND_TV_INPUT",
        "BIND_VISUAL_VOICEMAIL_SERVICE",
        "BIND_VOICE_INTERACTION",
        "BIND_VPN_SERVICE",
        "BIND_VR_LISTENER_SERVICE",
        "BIND_WALLPAPER",
        "BLUETOOTH",
        "BLUETOOTH_ADMIN",
        "BLUETOOTH_PRIVILEGED",
        "BODY_SENSORS",
        "BROADCAST_PACKAGE_REMOVED",
        "BROADCAST_SMS",
        "BROADCAST_STICKY",
        "BROADCAST_WAP_PUSH",
        "CALL_PHONE",
        "CALL_PRIVILEGED",
        "CAMERA",
        "CAPTURE_AUDIO_OUTPUT",
        "CAPTURE_SECURE_VIDEO_OUTPUT",
        "CAPTURE_VIDEO_OUTPUT",
        "CHANGE_COMPONENT_ENABLED_STATE",
        "CHANGE_CONFIGURATION",
        "CHANGE_NETWORK_STATE",
        "CHANGE_WIFI_MULTICAST_STATE",
        "CHANGE_WIFI_STATE",
        "CLEAR_APP_CACHE",
        "CONTROL_LOCATION_UPDATES",
        "DELETE_CACHE_FILES",
        "DELETE_PACKAGES",
        "DIAGNOSTIC",
        "DISABLE_KEYGUARD",
        "DUMP",
        "EXPAND_STATUS_BAR",
        "FACTORY_TEST",
        "GET_ACCOUNTS",
        "GET_ACCOUNTS_PRIVILEGED",
        "GET_PACKAGE_SIZE",
        "GET_TASKS",
        "GLOBAL_SEARCH",
        "INSTALL_LOCATION_PROVIDER",
        "INSTALL_PACKAGES",
        "INSTALL_SHORTCUT",
        "INSTANT_APP_FOREGROUND_SERVICE",
        "INTERNET",
        "KILL_BACKGROUND_PROCESSES",
        "LOCATION_HARDWARE",
        "MANAGE_DOCUMENTS",
        "MANAGE_OWN_CALLS",
        "MASTER_CLEAR",
        "MEDIA_CONTENT_CONTROL",
        "MODIFY_AUDIO_SETTINGS",
        "MODIFY_PHONE_STATE",
        "MOUNT_FORMAT_FILESYSTEMS",
        "MOUNT_UNMOUNT_FILESYSTEMS",
        "NFC",
        "PACKAGE_USAGE_STATS",
        "PERSISTENT_ACTIVITY",
        "PROCESS_OUTGOING_CALLS",
        "READ_CALENDAR",
        "READ_CALL_LOG",
        "READ_CONTACTS",
        "READ_EXTERNAL_STORAGE",
        "READ_FRAME_BUFFER",
        "READ_INPUT_STATE",
        "READ_LOGS",
        "READ_PHONE_NUMBER",
        "READ_PHONE_STATE",
        "READ_SMS",
        "READ_SYNC_SETTINGS",
        "READ_SYNC_STATS",
        "READ_VOICEMAIL",
        "REBOOT",
        "RECEIVE_BOOT_COMPLETED",
        "RECEIVE_MMS",
        "RECEIVE_SMS",
        "RECEIVE_WAP_PUSH",
        "RECORD_AUDIO",
        "REORDER_TASKS",
        "REQUEST_DELETE_PACKAGES",
        "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
        "REQUEST_INSTALL_PACKAGES",
        "RESTART_PACKAGES",
        "RESTRICTED_VR_ACCESS",
        "RUN_IN_BACKGROUND",
        "SEND_RESPOND_VIA_MESSAGE",
        "SEND_SMS",
        "SET_ALARM",
        "SET_ALWAYS_FINISH",
        "SET_ANIMATION_SCALE",
        "SET_DEBUG_APP",
        "SET_PREFERRED_APPLICATIONS",
        "SET_PROCESS_LIMIT",
        "SET_TIME",
        "SET_TIME_ZONE",
        "SET_WALLPAPER",
        "SET_WALLPAPER_HINTS",
        "SIGNAL_PERSISTENT_PROCESSES",
        "STATUS_BAR",
        "SYSTEM_ALERT_WINDOW",
        "TRANSMIT_IR",
        "UNINSTALL_SHORTCUT",
        "UPDATE_DEVICE_STATS",
        "USE_DATA_IN_BACKGROUND",
        "USE_FINGERPRINT",
        "USE_SIP",
        "VIBRATE",
        "WAKE_LOCK",
        "WRITE_APN_SETTINGS",
        "WRITE_CALENDAR",
        "WRITE_CALL_LOG",
        "WRITE_CONTACTS",
        "WRITE_EXTERNAL_STORAGE",
        "WRITE_GSERVICES",
        "WRITE_SECURE_SETTINGS",
        "WRITE_SETTINGS",
        "WRITE_SYNC_SETTINGS",
        "WRITE_VOICEMAIL",
    ]
)

DANGEROUS = frozenset(
    [
        "READ_CALENDAR",
        "WRITE_CALENDAR",
        "CAMERA",
        "READ_CONTACTS",
        "WRITE_CONTACTS",
        "GET_ACCOUNTS",
        "ACCESS_FINE_LOCATION",
        "ACCESS_COARSE_LOCATION",
        "RECORD_AUDIO",
        "READ_PHONE_STATE",
        "CALL_PHONE",
        "READ_CALL_LOG",
        "WRITE_CALL_LOG",
        "ADD_VOICEMAIL",
        "USE_SIP",
        "PROCESS_OUTGOING_CALLS",
        "BODY_SENSORS",
        "SEND_SMS",
        "RECEIVE_SMS",
        "READ_SMS",
        "RECEIVE_WAP_PUSH",
        "RECEIVE_MMS",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
    ]
)
