# -*- coding: utf-8 -*-
"""Retrieve pre-defined environment variables."""

import os

ENV_COUCH_ENDPOINT = "COUCH_ENDPOINT"
COUCH_ENDPOINT = os.environ.get(ENV_COUCH_ENDPOINT)

ENV_ELASTIC_URLS = "ELASTIC_URLS"
ELASTIC_URLS = os.environ.get(ENV_ELASTIC_URLS)

ENV_VIRUSTOTAL_APIKEY = "VIRUSTOTAL_APIKEY"
VIRUSTOTAL_APIKEY = os.environ.get(ENV_VIRUSTOTAL_APIKEY)

ENV_ANDROZOO_APIKEY = "ANDROZOO_APIKEY"
ANDROZOO_APIKEY = os.environ.get(ENV_ANDROZOO_APIKEY)

ENV_ANDROZOO_APIURL = "ANDROZOO_APIURL"
ANDROZOO_APIURL = os.environ.get(ENV_ANDROZOO_APIURL)

ENV_ANDROZOO_APIDIR = "ANDROZOO_APIDIR"
ANDROZOO_APIDIR = os.environ.get(ENV_ANDROZOO_APIDIR)

SUPPORT_ANDROZOO_LOCAL = ANDROZOO_APIDIR and os.path.exists(ANDROZOO_APIDIR)
